### PR TITLE
Assignment1: Kevin + Daniel

### PR DESCRIPTION
**Pull request by kflannery2001**
Partnered with @dpalmer10

### CODE REVIEW

**Comment by theRoice** [comment]
* Pull Request title includes "Assignment 1" in the title ✔
* Partner has also made a commit ✔
* Pull Request targets Assignment 1 branch ✔
* Issue 1: Application no longer crashes ✔
* Issue 2: Unit test properly passes ✔

## Extra Credit

* Come up with a new feature for the application
  * Issue 3: Add a new feature request implemented ❌
      No new feature request was implemented.
  * Issue 3: Feature request unit tested ❌
      No feature request unit tests were implemented.

**Comment by theRoice** [comment]
I don't have any specific comments regarding the code that was fixed, but I do have some ideas for the extra credit portion! Hopefully some of these sound interesting or fun to implement!

- Implement a leader-board. This could be as simple as having a high score for users to beat.
- Randomize the order the questions are presented in.
- Easy mode quiz. Give users the option to guess until they get the answer correct.

**Comment by dpalmer10** [comment]
A leaderboard keeping track of a high score is a good idea. An easy mode would also be worth looking into, thanks for the suggestions!

**Review by BenjaminMichaelis — COMMENTED** [review]
👍

**Pull request closed without merging**
